local config = {
  -- Fixed simulation world (cells). Window resize does not change these;
  -- Settings Apply can. Visual scale comes from baseVisualTile * camera.zoom.
  rows = 512,
  cols = 512,
  baseVisualTile = 24,
  -- Legacy alias used by layout helpers and older call sites; keep in sync with baseVisualTile.
  tileSize = 24,
  gridMode = "forced",
  forcedRows = 512,
  forcedCols = 512,
  forcedTileSize = 24,
  activeTheme = "solarized",
  activeRule = "conway",
  defaultPattern = "lifeview",
  stepInterval = 0.10,
  statusBarHeight = 28,
  paneWidth = 360,
  paneHeight = 120,
  paneBackdropAlpha = 0.55,
  paneScreenMargin = 8,
  stepAnimEnabled = true,
  stepAnimMinTileSize = 6,
  stepAnimPreviewSec = 0.08,
  stepAnimCommitSec = 0.12,
  buttonFxEnabled = true,
  buttonFxDurationSec = 0.4,
  buttonFxTrailCount = 3,
  buttonFxTrailSpacingSec = 0.05,
  buttonFxExpandPx = 10,
  cameraDefaultZoom = 1,
  cameraZoomMin = 0.05,
  cameraZoomMax = 8,
  cameraZoomStep = 1.25,
  toolbarMargin = 12,
  toolbarButtonSize = 32,
  previewDotScale = 0.15,
  previewDotMinPx = 4,
  tileDepthAlivePx = 3,
  tileDepthDeadPx = 0,
  accentBlendAlive = 0.72,
  accentBlendDead = 0.42,
}

return config
