local config = {
  -- Starting hints for conf.lua window size (also duplicated in conf.lua because
  -- fused builds cannot dofile inside .love); overridden at runtime by auto-fit.
  -- App startup pattern is defaultPattern below; patterns.lua uses "glider" as get() fallback only.
  rows = 40,
  cols = 60,
  tileSize = 24,
  gridMode = "auto",
  forcedRows = 40,
  forcedCols = 60,
  forcedTileSize = 24,
  activeTheme = "solarized",
  activeRule = "conway",
  defaultPattern = "lifeview",
  stepInterval = 0.10,
  statusBarHeight = 28,
  paneWidth = 360,
  paneHeight = 120,
  paneBackdropAlpha = 0.55,
  paneScreenMargin = 8,
  stepAnimEnabled = true,
  stepAnimMinTileSize = 6,
  stepAnimPreviewSec = 0.08,
  stepAnimCommitSec = 0.12,
  buttonFxEnabled = true,
  buttonFxDurationSec = 0.4,
  buttonFxTrailCount = 3,
  buttonFxTrailSpacingSec = 0.05,
  buttonFxExpandPx = 10,
  cameraDefaultZoom = 1,
  cameraZoomMin = 0.25,
  cameraZoomMax = 4,
  cameraZoomStep = 1.25,
  toolbarMargin = 12,
  toolbarButtonSize = 32,
  previewDotScale = 0.15,
  previewDotMinPx = 4,
  tileDepthAlivePx = 3,
  tileDepthDeadPx = 0,
  accentBlendAlive = 0.72,
  accentBlendDead = 0.42,
}

return config
